# MYSQL CONFIGURATION
SERVER.PORT=8090
spring.datasource.url=jdbc:mysql://localhost:3306/DSI
spring.datasource.username=root
spring.datasource.password=Rh5jF!-64Fi
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto = update  
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
security.jwt.secret-key=63a884bb7b74517c309f70534160bd38c8db147760c13559f1ebb0a694799347
security.jwt.expiration-time=3600000
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=paypalabiad@gmail.com
spring.mail.password=iwnr ywzp ytxb xzbv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

